version: ~> 1.0
language: java
os: linux

env:
  global:
  - M2_CACHE_CLEAN_DIR: "org/simplify4u/slf4j-mock**"
  - SONAR_ORG: "simplify4u"
  - MY_REPO: "s4u/slf4j-mock"

import:
  - source: s4u/travis:install.yml@master
  - source: s4u/travis:m2-cache.yml@master
  - source: s4u/travis:standard-jobs.yml@master
